### ISSUE TITLE
[BUG]data loss: using file/mvfile/seqfile

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#203]
eventgen.conf
> [film.json]
> disabled = false
> index = test_123
> count = 1000
> mode = sample
> outputMode = splunkstream
> interval = 10
> end = 1
> earliest = -1m
> autotimestamp = true
> sourcetype = _json
> sampletype = raw
> source = film.json
> outputMode = httpevent
> generatorWorkers =1
> httpeventServers = {"servers": [{"protocol": "https", "port": "8088", "key": "6ef943c6-cb4c-4763-abf8-1806cb825b6c", "address": "10.224.68.179"}]}
> httpeventOutputMode = mirror
> httpeventMaxPayloadSize = 10000
>
> token.0.token = "FILM_ID":(\d+)
> token.0.replacementType = integerid
> token.0.replacement = 0
> 
> token.1.token = "REGION_ID":(\d+)
> token.1.replacementType = seqfile
> token.1.replacement = /root/data/default/samples/count10.txt
> 
eventgen cmd:
`splunk_eventgen generate eventgen.conf`

content of count10.txt

> 0
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9

film.json(1K lines)

> {"FILM_ID":0,"DIRECTOR_ID":0,"REGION_ID":0,"TITLE":"CENTERDINOSAUR","DESCRIPTION":"ABeautifulCharacterStudyofaSumoWrestlerAndaDentistwhomustFindaDoginCalifornia","RELEASE_YEAR":2006,"LANGUAGE_ID":1,"ORIGINAL_LANGUAGE_ID":"(null)","RENTAL_DURATION":5,"RENTAL_RATE":4.99,"LENGTH":152,"REPLACEMENT_COST":12.99,"RATING":"PG","SPECIAL_FEATURES":"DeletedScenes","LAST_UPDATE":"2/15/0605:03"},

Expected results:
1000 events generated

Actual results:
910 events generated

**Comment by li-wu** [comment]
@YifengMao ,could you attache the bundle including `eventgen.conf` and sample files?

**Comment by YifengMao** [comment]
> @YifengMao ,could you attache the bundle including `eventgen.conf` and sample files?

already included in description

**Comment by jmeixensperger** [comment]
I was using a similar film.json file that I found in our large test samples to reproduce the issue, and I noticed that the first event was missing an opening bracket:

`"FILM_ID":0,"DIRECTOR_ID":0,"REGION_ID":0,"TITLE":"CENTERDINOSAUR","DESCRIPTION":"ABeautifulCharacterStudyofaSumoWrestlerAndaDentistwhomustFindaDoginCalifornia","RELEASE_YEAR":2006,"LANGUAGE_ID":1,"ORIGINAL_LANGUAGE_ID":"(null)","RENTAL_DURATION":5,"RENTAL_RATE":4.99,"LENGTH":152,"REPLACEMENT_COST":12.99,"RATING":"PG","SPECIAL_FEATURES":"DeletedScenes","LAST_UPDATE":"2/15/0605:03","_time":"Mon Jul 13 09:30:00 PDT 2017"},
`

I see all the events when I output to stdout or a file, and seqfile was not affecting the behavior. Eventgen was parsing the line as an event (which counts towards the 1000), however Splunk never indexes the event because of the json formatting. After fixing the json, I was able to generate all 1000 events with your eventgen.conf no problem.

Can you check your sample file for any json formatting errors or provide the full sample file for reference? I suspect this is the root cause.

**Comment by YifengMao** [comment]
@sjacobs-splunk i don't find any json misformat issues in my film.json.

Actually, if you use my eventgen.conf, and remove the lines of seqfile token replacement, it can produce 1000 events. (seqfile or mvfile both have this issue)

token.1.token = "REGION_ID":(\d+)
token.1.replacementType = seqfile
token.1.replacement = /root/data/default/samples/count10.txt

[film.txt](https://github.com/splunk/eventgen/files/3180759/film.txt)
please rename it to film.json

**Comment by li-wu** [comment]
I can not reproduce it with above conf and sample file with the latest version. I will show you tomorrow. @YifengMao
