### ISSUE TITLE
Parsing Event with Multiple Timestamps

### ISSUE THREAD

**Issue by ejrudy1** [splunk/eventgen#34]
I have a CSV file with multiple events in it of varying types. Some have multiple timestamps in them, and some do not. I see in the documentation that replayTimestamp can be useful if there are different timestamps in the same file, but in my case I have different timestamps in the same event (for example, Dec 12 and 2015/12/12 in the same event). Is there any functionality built in for this that perhaps I'm missing? Thanks!

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.

If you have multiple timestamp columns, that would be problemetic. If you have multiple timestamps in _raw column, you can define multiple regex rules to edit those timestamps.
