### ISSUE TITLE
transactional event generation

### ISSUE THREAD

**Issue by tkoeberl** [splunk/eventgen#38]
We want to generate transactional events. eg:
2016.03.17 11:43:12:372|START|**75124404**
2016.03.17 11:38:40:845|STOP|**75124404**
If we configure the eventgen to use INT to replace the "75124404" we get on each line a new integer, like:
2016.03.17 11:43:12:372|START|**75124400**
2016.03.17 11:38:40:845|STOP|**75124401**
With these numbers we cannnot correlate the transactions. Is it possbible to archive this with the current version?

thanks,
-tkoeberl

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.

This also seems like a usecase that can be solved by Jinja generator which is a new feature on 6.x.x.
