### ISSUE TITLE
Can we execute multiple input files in eventgen?

### ISSUE THREAD

**Issue by mcfabrero** [splunk/eventgen#53]
Hi,
Is it possible to run multiple input files in eventgen? I was just wondering how I can make
the eventgen run multiple files with different indexes and sourcetypes.
Can we have 2 eventgen configuration file stored in different folder,under the same app? one in local folder and one in newly created folder ?

Thanks!

**Comment by halr9000** [comment]
I would group your eventgen data configs first by technology/high level use case within each App. And for each app, in the default or local folder (these are combined/layered at runtime and have special meaning to Splunk, doesn't make sense to use them for another purpose), yes, you can definitely generate multiple datasets.

You do this by creating a new stanza in eventgen.conf for each. The stanza name will correspond to the file being read from the samples/ folder as mentioned in the docs [here](https://github.com/splunk/eventgen/blob/develop/README/Tutorial.md#the-config-file).

**Comment by mcfabrero** [comment]
Does it run the stanzas sequentially?
Thanks @halr9000

**Comment by halr9000** [comment]
When eventgen starts, it'll read the config, then create timers for each stanza found across all apps. So, no, they do not run sequentially, they run when they need to on multiple threads.

**Comment by bohrasaurabh** [comment]
mcfebrero,If you have how to questions about eventgen please post it on Splunk Communities Answers section. Use the tag as Eventgen...If there is a defect in eventgen which you have found feel free to post it here in Git. I just wanted to make sure you understand the difference between what Git and community Answers page is used for. Thanks,On Mar 2, 2017 12:08 AM, mcfabrero <notifications@github.com> wrote:Hi,
Is it possible to run multiple input files in eventgen? I was just wondering how it will work since I have 2 files with 2 different indexes and sourcetypes that should be populated with data coming from an eventgen.
Thanks!

**Comment by halr9000** [comment]
+1 to what @bohrasaurabh said. The # of folks who watch this issue list can probably be counted on one hand. Q&A is better on Answers or slack (splunk402.com/chat).

**Comment by mcfabrero** [comment]
Hi @bohrasaurabh 
This is noted.
