### ISSUE TITLE
Is it possible to get Eventgen to generate events based on a criteria?

### ISSUE THREAD

**Issue by luckyteos** [splunk/eventgen#78]
Hi there,

I would like to know whether it will be possible to get Eventgen to generate events based on a certain criteria, such as the severity level of an event, which is present in the event contained within the sample file. Currently I am mulling over an approach where I modify the events in the sample file to get them to be in a certain ratio to each other, such as Critical events having a ratio of 1 to normal events having a ratio of 100, then have Eventgen generate events based upon the distribution of events with different severity levels in the sample file. What do you guys think? Thanks and have a pleasant day ahead :)

**Comment by lephino** [comment]
Eventgen 6 has two main options for this, one a generator plugin, two, using the jinja templating.  I'm going to push you down the jinja route first, as it's a more elegant solution.  Please note, in order to use the jinja templating, you'll need to download the jinja library and place it in your sa-eventgen/lib dir.  If you use the python side, setup.py and pip will automatically install jinja for you.

There are some samples here: https://github.com/splunk/eventgen/tree/develop/tests/sample_eventgen_conf/jinja

what you'll see, is that the jinja plugin in eg6, gives the full power of the jinja templating language.  http://jinja.pocoo.org/docs/2.10/
This allows you to basically use templates that can be "based" on other things, and gives you the power of "if" and "for" statements directly inside of your logic.

for loop example: https://github.com/splunk/eventgen/blob/develop/tests/sample_eventgen_conf/jinja/templates/test_jinja_loop.template

complex template inheritance based on conditions:
https://github.com/splunk/eventgen/blob/develop/tests/sample_eventgen_conf/jinja/templates/test_jinja_advanced.template

If you decide to go the plugin route, eg6 greatly simplifies plugins.  Now, you just inherit from our base, and supply a gen method.  We'll take care of the rest!  Here's a short and sweet example of plugins:
https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/lib/plugins/generator/windbag.py

and likewise a complex plugin, jinja:
https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/lib/plugins/generator/jinja.py

part of the rework of eg6 was standardizing on the themes of the older version, and making the actual eg code line use the same things we ask the customers to use.  So now, even the most complex tokens in EG are just part of the "default" plugins.

**Comment by luckyteos** [comment]
Hi lephino, thanks for your lengthy reply, I appreciate it. Though do you have any idea if the same can be achieved in eventgen 4.0.0? Is it through the use of a plugin? As my existing splunk application is based off that, the eventgen.conf file for it does not seem to generate events using Eventgen 6.2.1. Thanks and have a pleasant day ahead :)

**Comment by lephino** [comment]
Sorry, i'm not sure, I didn't take over ownership of eventgen until 5.0, you'd have to look back on the old code and see if the plugins existed.  I haven't purged the master branch yet, but on the next update of eg 6, i'll be migrating master to the 6.x branch

**Comment by luckyteos** [comment]
Hi lephino, thanks for your reply. I am actually looking to see if it is possible to migrate the eventgen configuration for my application to work with Eventgen 6.2.1, however am running into issues with the eventgen.conf file with the outputMode = file. While the specification file says that a logFile option will be required if I use the file outputMode, there is no explanation as to what should I specify for logFile. Would like your advice on this. Thanks a lot :)

**Comment by lephino** [comment]
logFile = Path to the logfile you want to generate.  so something like: logFile=/tmp/eventgen_file.log. That output method is great if you want to test your props / transforms file of a TA or app.

**Comment by lephino** [comment]
um.... guilty! nothing, bug alert!  fileName is the only requirement, with some options:

https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/lib/plugins/output/file.py#L14
https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/lib/plugins/output/file.py#L20

Can you post the line in the doc to the old reference.  We'll get it fixed in the next release, or feel free to submit a pr on it.

**Comment by luckyteos** [comment]
Hi lephino,
The reference is actually part of the current develop branch available at https://github.com/splunk/eventgen/blob/develop/documentation/REFERENCE.md. This is the part I was talking about:
outputMode = modinput | s2s | file | splunkstream | stdout | devnull | spool | httpevent | syslogout | tcpout | udpout
    * Specifies how to output log data.  Modinput is default.
    * If setting spool, should set spoolDir
    * **If setting file, should set logFile**

**Comment by arctan5x** [comment]
PR made internally at Splunk. This repo will be updated at the next release.

I believe that Eventgen on master is 5.x version. Possibly 5.2?

**Comment by luckyteos** [comment]
Hi guys,
Thanks for your reply, I appreciate it. I saw the tutorial files have not changed in master and in the develop branch, would they be updated in the next release as well? Thanks in advance :)

**Comment by luckyteos** [comment]
Hi arctan5x,
Actually I am currently developing my splunk application with eventgen master, which is at version 5.x as mentioned by you. I have tried to get Eventgen 6.x to work with my application, but always run into the issue of getting no results, for something that has worked fine in previous versions. I am actually curious to know if there are working examples of eventgen.conf and sample files that I could use to try out eventgen 6.x (are they in tests?) and what changed that is breaking compatiblity with previous versions of Eventgen for eventgen.conf files written for previous versions of eventgen. Thanks :)

**Comment by arctan5x** [comment]
Eventgen 6.2.1 is in production. I am curious to see which config would break it since we tried to make it backward compatible and already runs a lot of old eventgen conf files without a problem. If you wouldn't mind, please post your eventgen.conf and other sample files so I can debug what is going on.

**Comment by luckyteos** [comment]
Hi guys,
I am not sure if I am doing it properly, as I am quite new to splunk application development, but the last time I tried to run eventgen on Ubuntu 16.04 with the configuration in the attached file below I observed that it generated events in eventgen versions 5.0 and below. However, trying it out earlier on my Ubuntu 18.04 VM running splunk 7.1.1, same splunk version as the VM on which eventgen generated events, it did not work even in versions 5 and earlier. I would like to use to use some help with the creation of a splunk app and using it with eventgen. What files (like for example inputs.conf) need to be configured to get eventgen to generate events, and does the metadata file affect anything? Thanks :)

Here's the link to the files 
https://drive.google.com/file/d/1nl7CFCMe0UFJ02MoLNBhDQ6yGHsBVR12/view?usp=sharing

**Comment by luckyteos** [comment]
Hi guys,
Any chance for review of this issue? Thanks :)

**Comment by arctan5x** [comment]
Reviewing today :)

**Comment by arctan5x** [comment]
Hi Luckyteos,

I tried generating with your eventgen.conf and samples, it worked flawlessly on my environment. Since it works on VMware but doesn't work on virtualbox, I don't think this is a problem with your conf file or your samples. 

How are you using Eventgen? Are you using it as a Splunk app or just a python module? If you are using it as a Splunk app, what kinds of Splunk are you using and what version is it? Can you also forward eventgen-* logs in /var/log/splunk?

In regards to writing your own plugin, what kinds of plugin are you looking to write? If you go into splunk_eventgen/lib/plugins, there are different types of plugins that you can take a look at.

Let me know 👍

**Comment by luckyteos** [comment]
Hi guys,

Thanks for your reply :) I am currently developing the next version of HP Printer Security, an older version of which is available on splunkbase [https://splunkbase.splunk.com/app/3588/]. My application uses eventgen to simulate printer events coming from a printer. Currently I am looking at how can I generate printer events based on severity levels without manually modifying the sample file. I have looked at the documentation for plugins but am a bit confused at what is the difference between output and generator types of plugins, because it seems to me like generator can do everything and thus am curious as to which type of plugin is better suited for what I want to do. Also, how did you get the eventgen file to work? I am thinking maybe its my application configuration or permission setting that is causing eventgen 6.2.1 to not work. Thanks in advance :)

**Comment by arctan5x** [comment]
Luckyteos,

As others suggested, Jinja is probably more flexible and easier to use for you use case. In Jinja, you can define mini macros (functions) as well so that you can generate printer events based on severity levels. Output plugin is just a mean to send your data to some specific place. If you look at tcpout.py, you can see that we make a socket connection to a provided address and port to send data. Generator data is probably what can help you. In there, you can modify a stream of data from your sample files. However, a well written Jinja should mostly replace your effort to write a custom generator plugin. 

In terms of your eventgen file, I got it to work easily. You always want to set an app permission to all for the app that contains eventgen.conf and samples. If you are really stuck, we can set up a video call so that I can help you debug on your environment. Let me know.

**Comment by luckyteos** [comment]
Hi arctan5x,
Thanks for your help so far. I have got my application to work with eventgen 6.2.1, albiet after changing outputMode = splunkstream, because I suspect due to a linux system permissions issue, the files are not getting written to the data folder in my application. Will be looking into how to use jinja to generate events by severity type next. Once again, thanks to you guys for all your help, I appreciate it :)

**Comment by arctan5x** [comment]
Glad you got your application to work. Can we close out the issue?

**Comment by luckyteos** [comment]
```
Hi guys, 

I’m reopening this issue after doing some reading of jinja and looking through the sample jinja templates available on github to ask, what are the variables that are available to me by eventgen when using jinja, and how do I sort of access the sample file that eventgen sees through jinja (the severity field) so as to generate events by severity type as I see in some of the sample template files variables like time_now are used, but don’t know where they come from
Thanks in advance and I would gladly appreciate your help with this :)
```

**Comment by arctan5x** [comment]
Luckyteos,

Not sure if you can pass in the entire sample file through Jinja. If you have a list of severity field, you can defined that in Jinja. For example, {% set severity_list = [1,2,3,4] %}. Or, you can specify your variables in eventgen.conf. Take a look at tests/sample_eventgen_conf/jinja/eventgen.conf.jinja. You can see the key "jinja__variables". These variables will be accessible in your template.

**Comment by arctan5x** [comment]
Otherwise, Jinja tem

**Comment by arctan5x** [comment]
Closing for now. If the problem persists, please reopen.
